import AppKit
import SwiftUI
import YCodeCore

struct YCodeLocalization {
    var locale: YCodeLocale

    func text(_ key: String) -> String {
        Self.translations[key]?[locale] ?? key
    }

    func text(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), arguments: arguments)
    }

    static let zh = YCodeLocalization(locale: .zh)

    static let translations: [String: [YCodeLocale: String]] = [
        "workspace": [.zh: "工作区", .en: "Workspace"],
        "settings": [.zh: "设置", .en: "Settings"],
        "cancel": [.zh: "取消", .en: "Cancel"],
        "save": [.zh: "保存", .en: "Save"],
        "restoreDefaults": [.zh: "恢复默认", .en: "Restore Defaults"],
        "ok": [.zh: "好", .en: "OK"],
        "addProject": [.zh: "添加项目", .en: "Add Project"],
        "addProjectEllipsis": [.zh: "添加项目…", .en: "Add Project..."],
        "newSession": [.zh: "新建会话", .en: "New Session"],
        "newAgentSession": [.zh: "新建 Agent 会话", .en: "New Agent Session"],
        "newAgentSessionEllipsis": [.zh: "新建 Agent 会话…", .en: "New Agent Session..."],
        "projectOverview": [.zh: "项目总览", .en: "Project Overview"],
        "openSeparateWindow": [.zh: "在独立窗口打开", .en: "Open in Separate Window"],
        "moveUp": [.zh: "向上移动", .en: "Move Up"],
        "moveDown": [.zh: "向下移动", .en: "Move Down"],
        "showHideProjectSidebar": [.zh: "显示/隐藏项目侧栏", .en: "Show/Hide Project Sidebar"],
        "findCurrentTerminal": [.zh: "查找当前终端…", .en: "Find Current Terminal..."],
        "searchProjectHistory": [.zh: "搜索当前项目历史…", .en: "Search Project History..."],
        "refreshHistory": [.zh: "刷新历史", .en: "Refresh History"],
        "attentionInbox": [.zh: "关注收件箱", .en: "Attention Inbox"],
        "openAttentionInbox": [.zh: "打开关注收件箱", .en: "Open Attention Inbox"],
        "showBuildInfo": [.zh: "显示构建信息", .en: "Show Build Info"],
        "checkForUpdatesEllipsis": [.zh: "检查更新…", .en: "Check for Updates..."],
        "updatesReleaseOnly": [.zh: "更新仅在配置签名更新源的发布版中启用。", .en: "Updates are enabled only in release builds configured with a signed feed."],
        "project": [.zh: "项目", .en: "Project"],
        "projects": [.zh: "项目", .en: "Projects"],
        "session": [.zh: "会话", .en: "Session"],
        "sessions": [.zh: "会话", .en: "Sessions"],
        "workspaceMenu": [.zh: "工作区", .en: "Workspace"],
        "history": [.zh: "历史", .en: "History"],
        "attention": [.zh: "关注", .en: "Attention"],
        "migration": [.zh: "迁移", .en: "Migration"],
        "showHidePanelFormat": [.zh: "显示/隐藏%@面板", .en: "Show/Hide %@ Panel"],
        "focusCanvasFormat": [.zh: "聚焦画布 %d", .en: "Focus Canvas %d"],
        "terminal": [.zh: "终端", .en: "Terminal"],
        "files": [.zh: "文件", .en: "Files"],
        "changes": [.zh: "变更", .en: "Changes"],
        "todos": [.zh: "待办", .en: "Todos"],
        "noProjectSelected": [.zh: "未选择项目", .en: "No Project Selected"],
        "chooseOrCreateSession": [.zh: "选择或新建会话", .en: "Select or Create a Session"],
        "upTo4AgentTerminals": [.zh: "最多可同时显示 4 个 Agent 终端", .en: "Show up to 4 agent terminals at once"],
        "showHidePanelHelpFormat": [.zh: "显示/隐藏%@面板", .en: "Show or hide the %@ panel"],
        "smallerTerminalFont": [.zh: "缩小终端字号", .en: "Smaller terminal font"],
        "largerTerminalFont": [.zh: "放大终端字号", .en: "Larger terminal font"],
        "newSessionFallback": [.zh: "新会话", .en: "New Session"],
        "findTerminal": [.zh: "查找终端", .en: "Find Terminal"],
        "hideDoNotStopAgent": [.zh: "从画布隐藏；不停止 Agent", .en: "Hide from canvas; do not stop the agent"],
        "noMatches": [.zh: "无匹配", .en: "No Matches"],
        "agentNotRunning": [.zh: "Agent 未运行", .en: "Agent Not Running"],
        "lastExitStatusFormat": [.zh: "上次退出状态：%d", .en: "Last exit status: %d"],
        "canRecoverOriginalSession": [.zh: "可从原会话恢复", .en: "Can recover from original session"],
        "recoverSession": [.zh: "恢复会话", .en: "Recover Session"],
        "shellUnavailable": [.zh: "Shell 不可用", .en: "Shell Unavailable"],
        "selectProjectFirst": [.zh: "请先选择一个项目", .en: "Select a project first"],
        "splitRight": [.zh: "向右分屏", .en: "Split Right"],
        "splitDown": [.zh: "向下分屏", .en: "Split Down"],
        "splitLeft": [.zh: "向左分屏", .en: "Split Left"],
        "splitUp": [.zh: "向上分屏", .en: "Split Up"],
        "split": [.zh: "分屏", .en: "Split"],
        "closeShellPane": [.zh: "关闭面板并停止这个 Shell", .en: "Close pane and stop this shell"],
        "shellExited": [.zh: "Shell 已退出", .en: "Shell Exited"],
        "restart": [.zh: "重新启动", .en: "Restart"],
        "fileTree": [.zh: "文件树", .en: "File Tree"],
        "jumpToDefinition": [.zh: "跳转定义", .en: "Go to Definition"],
        "jumpToDefinitionHelp": [.zh: "按当前光标位置跳转定义", .en: "Go to definition at the current cursor"],
        "preview": [.zh: "预览", .en: "Preview"],
        "source": [.zh: "源码", .en: "Source"],
        "imagePreview": [.zh: "图片预览", .en: "Image Preview"],
        "unsaved": [.zh: "未保存", .en: "Unsaved"],
        "saved": [.zh: "已保存", .en: "Saved"],
        "close": [.zh: "关闭", .en: "Close"],
        "discardAndClose": [.zh: "丢弃修改并关闭", .en: "Discard Changes and Close"],
        "discardMessage": [.zh: "上次保存后的修改会丢失。", .en: "Changes since the last save will be lost."],
        "reloadDiskVersion": [.zh: "重新加载磁盘版本", .en: "Reload Disk Version"],
        "overwriteDiskVersion": [.zh: "覆盖磁盘版本", .en: "Overwrite Disk Version"],
        "saveConflict": [.zh: "保存冲突", .en: "Save Conflict"],
        "saveConflictMessage": [.zh: "普通保存不会覆盖外部修改。重新加载会丢弃当前草稿；覆盖只会在明确选择后执行。", .en: "Normal save will not overwrite external changes. Reload discards the current draft; overwrite only happens after explicit confirmation."],
        "opening": [.zh: "正在打开…", .en: "Opening..."],
        "cannotOpenFile": [.zh: "无法打开文件", .en: "Cannot Open File"],
        "cannotPreviewImage": [.zh: "无法预览图片", .en: "Cannot Preview Image"],
        "imageCorrupt": [.zh: "图片内容损坏或格式不受系统支持", .en: "The image is damaged or not supported by the system"],
        "cannotPreviewSVG": [.zh: "无法预览 SVG", .en: "Cannot Preview SVG"],
        "invalidSVG": [.zh: "SVG 内容无效；可切换到源码修复", .en: "The SVG is invalid; switch to source to fix it"],
        "binaryFile": [.zh: "二进制文件", .en: "Binary File"],
        "binaryNotEditable": [.zh: "此文件不能作为 UTF-8 文本编辑", .en: "This file cannot be edited as UTF-8 text"],
        "fileDeletedDraftKept": [.zh: "文件已从磁盘删除；当前草稿仍保留。", .en: "The file was deleted on disk; the current draft is kept."],
        "fileChangedOnDisk": [.zh: "文件在磁盘上已改变；当前草稿尚未覆盖它。", .en: "The file changed on disk; the current draft has not overwritten it."],
        "reload": [.zh: "重新加载", .en: "Reload"],
        "saveEllipsis": [.zh: "保存…", .en: "Save..."],
        "branch": [.zh: "分支", .en: "Branch"],
        "noChanges": [.zh: "没有变更", .en: "No Changes"],
        "stage": [.zh: "暂存", .en: "Stage"],
        "unstage": [.zh: "取消暂存", .en: "Unstage"],
        "discard": [.zh: "丢弃", .en: "Discard"],
        "commitStagedChanges": [.zh: "提交已暂存变更", .en: "Commit Staged Changes"],
        "createTodoHint": [.zh: "在上方输入后按 Return 添加。", .en: "Type above and press Return to add."],
        "done": [.zh: "已完成", .en: "Done"],
        "renameTodo": [.zh: "重命名待办", .en: "Rename Todo"],
        "deleteTodoQuestion": [.zh: "删除待办？", .en: "Delete Todo?"],
        "delete": [.zh: "删除", .en: "Delete"],
        "refreshTodos": [.zh: "刷新待办", .en: "Refresh Todos"],
        "addTodo": [.zh: "添加待办", .en: "Add Todo"],
        "renameEllipsis": [.zh: "重命名…", .en: "Rename..."],
        "deleteEllipsis": [.zh: "删除…", .en: "Delete..."],
        "rename": [.zh: "重命名", .en: "Rename"],
        "newFile": [.zh: "新建文件", .en: "New File"],
        "newFolder": [.zh: "新建文件夹", .en: "New Folder"],
        "refresh": [.zh: "刷新", .en: "Refresh"],
        "revealInFinder": [.zh: "在访达中显示", .en: "Reveal in Finder"],
        "openExternalEditor": [.zh: "在外部编辑器中打开", .en: "Open in External Editor"],
        "emptyFolder": [.zh: "空文件夹", .en: "Empty Folder"],
        "createFileOrFolder": [.zh: "可在此创建文件或文件夹", .en: "Create a file or folder here"],
        "locationFormat": [.zh: "位置：%@", .en: "Location: %@"],
        "folderDeleteWarning": [.zh: "文件夹及其全部内容会被删除，此操作无法撤销。", .en: "The folder and all contents will be deleted. This cannot be undone."],
        "deleteWarning": [.zh: "此操作无法撤销。", .en: "This cannot be undone."],
        "general": [.zh: "通用", .en: "General"],
        "panels": [.zh: "面板", .en: "Panels"],
        "agents": [.zh: "Agent", .en: "Agents"],
        "integrations": [.zh: "集成", .en: "Integrations"],
        "notifications": [.zh: "通知", .en: "Notifications"],
        "usage": [.zh: "用量", .en: "Usage"],
        "languages": [.zh: "语言服务", .en: "Language Services"],
        "appearance": [.zh: "外观", .en: "Appearance"],
        "keyboard": [.zh: "键盘", .en: "Keyboard"],
        "data": [.zh: "数据", .en: "Data"],
        "about": [.zh: "关于", .en: "About"],
        "startup": [.zh: "启动", .en: "Startup"],
        "showAtStartup": [.zh: "启动时显示", .en: "Show at startup"],
        "resumeRecentWorkspace": [.zh: "恢复最近工作区", .en: "Resume Recent Workspace"],
        "blankRecentProjectWorkspace": [.zh: "最近项目空白工作区", .en: "Blank Workspace for Recent Project"],
        "startupTakesEffectNextLaunch": [.zh: "设置在下次启动时生效。现阶段不会自动启动 Agent。", .en: "This takes effect on next launch. Agents are not auto-started at this stage."],
        "sessionLifetime": [.zh: "会话生命周期", .en: "Session Lifetime"],
        "keepPTY": [.zh: "常驻 PTY", .en: "Keep PTY Alive"],
        "keepPTYPending": [.zh: "原版尚未实现常驻 PTY；此开关保持禁用。", .en: "The legacy app never implemented persistent PTYs; this control remains disabled."],
        "idleReaping": [.zh: "空闲回收", .en: "Idle Reaping"],
        "after30Minutes": [.zh: "30 分钟后", .en: "After 30 Minutes"],
        "after2Hours": [.zh: "2 小时后", .en: "After 2 Hours"],
        "idleReapingPending": [.zh: "原版空闲回收选项尚未实现，当前恒为关闭。", .en: "The legacy idle-reaping choices were not implemented and remain off."],
        "archive": [.zh: "归档", .en: "Archive"],
        "automaticArchive": [.zh: "自动归档", .en: "Automatic Archive"],
        "automaticArchivePending": [.zh: "原版尚未实现自动归档；当前只支持手动归档。", .en: "The legacy app never implemented automatic archiving; manual archive remains available."],
        "migratedInterfaceState": [.zh: "已迁移的界面状态", .en: "Migrated Interface State"],
        "fileTreeWidth": [.zh: "文件树宽度", .en: "File Tree Width"],
        "importedWidthUsed": [.zh: "导入的旧版宽度现在作为文件面板的初始宽度。", .en: "Imported legacy width is used as the initial file panel width."],
        "configured": [.zh: "已配置", .en: "Configured"],
        "noAgentsConfigured": [.zh: "没有配置 Agent；仍可保存此状态。", .en: "No agents configured; this state can still be saved."],
        "detected": [.zh: "已检测到", .en: "Detected"],
        "add": [.zh: "添加", .en: "Add"],
        "addCustomAgent": [.zh: "添加自定义 Agent…", .en: "Add Custom Agent..."],
        "agentIcon": [.zh: "图标", .en: "Icon"],
        "agentIconKey": [.zh: "图标键", .en: "Icon Key"],
        "agentIconKeyHelp": [.zh: "可选择白名单图标，也可输入未知键验证字母占位回落。", .en: "Choose a whitelisted icon or enter an unknown key to verify the letter fallback."],
        "agentIconNone": [.zh: "无（字母占位）", .en: "None (Letter Placeholder)"],
        "agentIconVariant": [.zh: "图标样式", .en: "Icon Style"],
        "agentIconBrand": [.zh: "品牌色", .en: "Brand Color"],
        "agentIconMono": [.zh: "单色", .en: "Monochrome"],
        "agentColor": [.zh: "强调色", .en: "Accent Color"],
        "clearAgentColor": [.zh: "清除颜色", .en: "Clear Color"],
        "agentHelp": [.zh: "命令允许先保存后安装；启动时找不到程序会显示明确错误。环境变量值可写成 $变量名，只有启动时才解析。", .en: "Commands can be saved before installation; missing programs show clear launch errors. Environment values may use $VARIABLE and are resolved only at launch."],
        "launchEnvironment": [.zh: "启动环境", .en: "Launch Environment"],
        "terminalCapabilities": [.zh: "终端能力", .en: "Terminal Capabilities"],
        "proxy": [.zh: "代理", .en: "Proxy"],
        "mode": [.zh: "模式", .en: "Mode"],
        "off": [.zh: "关闭", .en: "Off"],
        "followSystem": [.zh: "跟随系统", .en: "Follow System"],
        "manual": [.zh: "手动", .en: "Manual"],
        "currentDetection": [.zh: "当前检测", .en: "Current Detection"],
        "proxyAddress": [.zh: "代理地址", .en: "Proxy Address"],
        "exceptions": [.zh: "例外", .en: "Exceptions"],
        "proxyHelp": [.zh: "系统模式只补充缺失值；手动模式覆盖继承值。Shell 启动脚本中的 export 最终优先。", .en: "System mode only fills missing values; manual mode overrides inherited values. Exports in shell startup scripts still win last."],
        "theme": [.zh: "主题", .en: "Theme"],
        "unknownTheme": [.zh: "未知主题", .en: "Unknown Theme"],
        "themeHelp": [.zh: "主题色板会应用到主界面、编辑器与终端；未知主题 ID 会原样保存，旧版或后续版本仍可识别。", .en: "Theme palettes apply to the main UI, editor, and terminal. Unknown theme IDs are preserved for legacy or future versions."],
        "language": [.zh: "语言", .en: "Language"],
        "interfaceLanguage": [.zh: "界面语言", .en: "Interface Language"],
        "languageHelp": [.zh: "保存后主窗口、设置和已迁移面板会按所选语言刷新。", .en: "After saving, the main window, settings, and migrated panels refresh in the selected language."],
        "fontSize": [.zh: "字号", .en: "Font Size"],
        "interface": [.zh: "界面", .en: "Interface"],
        "editor": [.zh: "编辑器", .en: "Editor"],
        "fontHelp": [.zh: "非预设字号会按 8–32 pt 范围保留，并应用到界面、编辑器和终端。", .en: "Non-preset font sizes are preserved within 8-32 pt and applied to the UI, editor, and terminal."],
        "currentShortcuts": [.zh: "当前快捷键", .en: "Current Shortcuts"],
        "shortcutsReadOnly": [.zh: "原版没有可编辑快捷键映射；此处只展示已迁移快捷键，不提供无效开关。", .en: "The legacy app did not have editable shortcut mappings; this only lists migrated shortcuts, with no fake toggles."],
        "nativeData": [.zh: "原生数据", .en: "Native Data"],
        "dataDirectory": [.zh: "数据目录", .en: "Data Directory"],
        "legacyDataUnchanged": [.zh: "旧版数据保持不变；当前应用使用迁移副本。", .en: "Legacy data is unchanged; the current app uses the migrated copy."],
        "versionFormat": [.zh: "版本 %@", .en: "Version %@"],
        "updates": [.zh: "更新", .en: "Updates"],
        "updateChannel": [.zh: "更新渠道", .en: "Update Channel"],
        "stableChannel": [.zh: "稳定版", .en: "Stable"],
        "automaticUpdateDownloads": [.zh: "自动下载更新", .en: "Automatically Download Updates"],
        "updateOptionsPending": [.zh: "原版尚未实现更新渠道和自动下载；这些选项保持禁用。", .en: "The legacy app never implemented update channels or automatic downloads; these options remain disabled."],
        "viewLicenses": [.zh: "查看许可证", .en: "View Licenses"],
        "licensesPending": [.zh: "原版许可证入口尚未实现，当前不可用。", .en: "The legacy license viewer was not implemented and remains unavailable."],
        "sectionUnavailableFormat": [.zh: "%@设置尚未接入", .en: "%@ Settings Not Connected"],
        "sectionStageFormat": [.zh: "按迁移计划在 %@ 实现；当前没有无效开关或伪功能。", .en: "Planned for %@; there are no fake toggles or placeholder features here."],
        "settingsSaveFailed": [.zh: "设置保存失败", .en: "Failed to Save Settings"],
        "unknownError": [.zh: "未知错误", .en: "Unknown Error"],
        "available": [.zh: "可用", .en: "Available"],
        "notFound": [.zh: "未找到", .en: "Not Found"]
        ,
        "externalOpenFailed": [.zh: "无法处理外部打开请求", .en: "Cannot handle external open request"],
        "renameSession": [.zh: "重命名会话", .en: "Rename Session"],
        "name": [.zh: "名称", .en: "Name"],
        "buildInfo": [.zh: "构建信息", .en: "Build Info"],
        "buildInfoMessageFormat": [.zh: "%@\n开发标识：%@\n发布架构：%@", .en: "%@\nDevelopment ID: %@\nRelease Architectures: %@"],
        "errorOccurred": [.zh: "发生错误", .en: "Error"],
        "removeProject": [.zh: "移除项目", .en: "Remove Project"],
        "removeProjectTitleFormat": [.zh: "从 YCode 移除“%@”？", .en: "Remove \"%@\" from YCode?"],
        "removeProjectMessage": [.zh: "只删除 YCode 中的记录，不删除磁盘目录、worktree 或分支。之后仍可重新添加。", .en: "Only the YCode record is removed. Disk folders, worktrees, and branches are not deleted. You can add it again later."],
        "archiveTitleFormat": [.zh: "归档“%@”？", .en: "Archive \"%@\"?"],
        "stopAndArchive": [.zh: "停止并归档", .en: "Stop and Archive"],
        "archiveMessage": [.zh: "会停止正在运行的 Agent 并隐藏该会话；项目文件不会被删除。", .en: "This stops the running agent and hides the session; project files are not deleted."],
        "liveSessionCountFormat": [.zh: "%d 个当前会话", .en: "%d live sessions"],
        "noProjectsYet": [.zh: "还没有项目", .en: "No Projects Yet"],
        "addProjectShortcutHint": [.zh: "使用 ⌘O 添加项目目录", .en: "Use ⌘O to add a project folder"],
        "noSessions": [.zh: "没有会话", .en: "No Sessions"],
        "newSessionShortcutHint": [.zh: "使用 ⌘N 启动 Agent", .en: "Use ⌘N to start an agent"],
        "normalSessions": [.zh: "普通会话", .en: "Normal Sessions"],
        "isolatedUnsupportedSessions": [.zh: "隔离会话 · 暂不支持恢复", .en: "Isolated Sessions · Restore Not Supported"],
        "metadataOnlyWorktree": [.zh: "保留元数据；不恢复或删除 worktree", .en: "Metadata retained; worktree is not restored or deleted"],
        "process": [.zh: "进程", .en: "Process"],
        "stop": [.zh: "停止", .en: "Stop"],
        "recoverRestart": [.zh: "恢复 / 重启", .en: "Recover / Restart"],
        "archiveEllipsis": [.zh: "归档…", .en: "Archive..."],
        "projectPathMissing": [.zh: "项目路径当前不存在", .en: "Project path does not currently exist"],
        "currentSessions": [.zh: "当前会话", .en: "Current Sessions"],
        "allRecords": [.zh: "全部记录", .en: "All Records"],
        "isolationSwitchRecord": [.zh: "隔离开关记录", .en: "Isolation Switch Record"],
        "preservedNotRun": [.zh: "保留（首版不执行）", .en: "Preserved (not run in first native version)"],
        "closed": [.zh: "关闭", .en: "Off"],
        "fileTreeWidthEffective": [.zh: "%d px（M4.1 生效）", .en: "%d px (active since M4.1)"],
        "dataDirectoryFormat": [.zh: "数据目录：%@", .en: "Data directory: %@"],
        "projectInfo": [.zh: "项目信息", .en: "Project Info"],
        "overview": [.zh: "总览", .en: "Overview"],
        "nativeProjectOverview": [.zh: "原生项目总览", .en: "Native Project Overview"],
        "separateWindow": [.zh: "独立窗口", .en: "Separate Window"],
        "attentionUnreadFormat": [.zh: "关注 %d", .en: "Attention %d"],
        "unreadAttentionFormat": [.zh: "%d 个未读关注项", .en: "%d unread attention items"],
        "pendingApproval": [.zh: "待批准", .en: "Needs Approval"],
        "waitingInput": [.zh: "等待输入", .en: "Waiting for Input"],
        "running": [.zh: "运行中", .en: "Running"],
        "starting": [.zh: "启动中", .en: "Starting"],
        "exitedFormat": [.zh: "已退出 %@", .en: "Exited %@"],
        "stoppedSignalFormat": [.zh: "已停止 SIG%d", .en: "Stopped SIG%d"],
        "recoverable": [.zh: "可恢复", .en: "Recoverable"],
        "sessionName": [.zh: "会话名称", .en: "Session Name"],
        "addAgentFirst": [.zh: "请先在设置中添加 Agent", .en: "Add an agent in Settings first"],
        "start": [.zh: "启动", .en: "Start"],
        "searchHistoryBody": [.zh: "搜索历史正文", .en: "Search history text"],
        "search": [.zh: "搜索", .en: "Search"],
        "rescan": [.zh: "重新扫描", .en: "Rescan"],
        "searching": [.zh: "正在搜索…", .en: "Searching..."],
        "foundResultsFormat": [.zh: "找到 %d 条结果", .en: "Found %d results"],
        "noMatchingResults": [.zh: "没有匹配结果", .en: "No Matching Results"],
        "restoreThisSession": [.zh: "恢复此会话", .en: "Restore This Session"],
        "restore": [.zh: "恢复", .en: "Restore"],
        "restoreOriginalAgentSession": [.zh: "用原 Agent 会话 ID 恢复到终端", .en: "Restore to the terminal with the original agent session ID"],
        "reading": [.zh: "正在读取…", .en: "Reading..."],
        "noHistorySessions": [.zh: "没有历史会话", .en: "No History Sessions"],
        "noProjectJSONL": [.zh: "当前项目没有 Claude 或 Codex JSONL", .en: "Current project has no Claude or Codex JSONL"],
        "noDisplayableEvents": [.zh: "会话没有可展示事件", .en: "Session has no displayable events"],
        "user": [.zh: "用户", .en: "User"],
        "assistant": [.zh: "助手", .en: "Assistant"],
        "thinking": [.zh: "思考", .en: "Thinking"],
        "toolCallFormat": [.zh: "调用 · %@", .en: "Call · %@"],
        "toolResultFormat": [.zh: "结果 · %@", .en: "Result · %@"],
        "other": [.zh: "其他", .en: "Other"],
        "readingTodos": [.zh: "正在读取待办…", .en: "Reading todos..."],
        "doing": [.zh: "进行中", .en: "Doing"],
        "queue": [.zh: "队列", .en: "Queue"],
        "noActiveTodos": [.zh: "没有进行中的待办", .en: "No Active Todos"],
        "title": [.zh: "标题", .en: "Title"],
        "reopen": [.zh: "重新打开", .en: "Reopen"],
        "markDone": [.zh: "标记完成", .en: "Mark Done"],
        "started": [.zh: "开始", .en: "Started"],
        "completed": [.zh: "完成", .en: "Completed"],
        "added": [.zh: "添加", .en: "Added"],
        "justNowFormat": [.zh: "%@于刚刚", .en: "%@ just now"],
        "relativeTimeFormat": [.zh: "%@于 %@", .en: "%@ %@"],
        "createdAtFormat": [.zh: "创建：%@", .en: "Created: %@"],
        "startedAtFormat": [.zh: "开始：%@", .en: "Started: %@"],
        "completedAtFormat": [.zh: "完成：%@", .en: "Completed: %@"],
        "doubleClickRename": [.zh: "双击标题可重命名", .en: "Double-click title to rename"],
        "gitUnavailable": [.zh: "Git 不可用", .en: "Git Unavailable"],
        "refreshGitStatus": [.zh: "刷新 Git 状态", .en: "Refresh Git Status"],
        "fromPathFormat": [.zh: "从 %@", .en: "From %@"],
        "commitMessage": [.zh: "提交信息", .en: "Commit Message"],
        "selectFileForDiff": [.zh: "选择文件查看 diff", .en: "Select a file to view diff"],
        "checkpoints": [.zh: "检查点", .en: "Checkpoints"],
        "refreshCheckpoints": [.zh: "刷新检查点", .en: "Refresh Checkpoints"],
        "selectSessionForCheckpoints": [.zh: "选择会话以查看检查点", .en: "Select a session to view checkpoints"],
        "noCheckpoints": [.zh: "没有检查点", .en: "No Checkpoints"],
        "checkpointCountFormat": [.zh: "%d 个检查点", .en: "%d checkpoints"],
        "checkpointEmptyDiff": [.zh: "该轮文件内容无变化", .en: "No file content changes in this turn"],
        "selectCheckpointForDiff": [.zh: "选择检查点查看逐轮 diff", .en: "Select a checkpoint to view its diff"],
        "initialCheckpoint": [.zh: "初始", .en: "Initial"],
        "turnCheckpoint": [.zh: "轮次", .en: "Turn"],
        "readingUsage": [.zh: "正在统计用量…", .en: "Calculating usage..."],
        "cannotReadUsage": [.zh: "无法读取用量", .en: "Cannot Read Usage"],
        "noUsageRecords": [.zh: "没有用量记录", .en: "No Usage Records"],
        "noTokenHistory": [.zh: "已注册项目中没有带 Token 统计的 Claude 或 Codex 历史。", .en: "Registered projects have no Claude or Codex history with token statistics."],
        "recalculate": [.zh: "重新统计", .en: "Recalculate"],
        "usageEstimateHelp": [.zh: "读取 Agent 自己保存的历史记录；费用按 2026 年 6 月公开单价离线估算，不等同于账单。", .en: "Reads the agent's own saved history. Cost is estimated offline from public June 2026 pricing and is not a bill."],
        "estimatedCost": [.zh: "估算费用", .en: "Estimated Cost"],
        "totalTokens": [.zh: "总 Token", .en: "Total Tokens"],
        "input": [.zh: "输入", .en: "Input"],
        "output": [.zh: "输出", .en: "Output"],
        "cacheWrite": [.zh: "缓存写入", .en: "Cache Write"],
        "cacheRead": [.zh: "缓存读取", .en: "Cache Read"],
        "reasoning": [.zh: "推理", .en: "Reasoning"],
        "byProject": [.zh: "按项目", .en: "By Project"],
        "recentUsageUTC": [.zh: "最近使用日期（UTC）", .en: "Recent Usage Dates (UTC)"],
        "byModel": [.zh: "按模型", .en: "By Model"],
        "sessionCountFormat": [.zh: "%d 个会话 · %@ Token", .en: "%d sessions · %@ tokens"],
        "unknownModel": [.zh: "未知模型", .en: "Unknown Model"],
        "notificationLoading": [.zh: "读取中…", .en: "Loading..."],
        "always": [.zh: "始终", .en: "Always"],
        "onlyUnfocused": [.zh: "仅在后台", .en: "Only in Background"],
        "deliveryTiming": [.zh: "发送时机", .en: "Delivery Timing"],
        "testNotification": [.zh: "测试通知", .en: "Test Notification"],
        "send": [.zh: "发送", .en: "Send"],
        "notificationAccepted": [.zh: "通知中心已接收", .en: "Notification Center accepted it"],
        "systemPermission": [.zh: "系统权限", .en: "System Permission"],
        "recentTest": [.zh: "最近测试", .en: "Recent Test"],
        "systemNotifications": [.zh: "系统通知", .en: "System Notifications"],
        "notificationsHelp": [.zh: "“仅在后台”会在任意 YCode 窗口处于前台时保持安静；关注收件箱仍会更新。", .en: "\"Only in Background\" stays quiet while any YCode window is foreground; the attention inbox still updates."],
        "connectedEvents": [.zh: "已接入事件", .en: "Connected Events"],
        "agentTurnComplete": [.zh: "Agent 完成一轮", .en: "Agent turn complete"],
        "enabled": [.zh: "已启用", .en: "Enabled"],
        "needsApprovalOrAttention": [.zh: "需要批准或关注", .en: "Needs approval or attention"],
        "notificationApprovalHelp": [.zh: "通知只提示并跳转到原终端，不会代替你批准 Agent 操作。", .en: "Notifications only alert and jump to the original terminal; they do not approve agent actions for you."],
        "notificationFailed": [.zh: "通知发送失败", .en: "Notification Failed"],
        "languageServerHelp": [.zh: "语言服务器为编辑器提供语义高亮和定义跳转。安装目录与当前原生数据目录隔离。", .en: "Language servers provide semantic highlighting and go-to-definition. Installations are isolated under the current native data directory."],
        "fileLabel": [.zh: "文件：", .en: "Files:"],
        "missingCommandsFormat": [.zh: "缺少命令：%@", .en: "Missing commands: %@"],
        "learnMore": [.zh: "了解更多", .en: "Learn More"],
        "uninstall": [.zh: "卸载", .en: "Uninstall"],
        "install": [.zh: "安装", .en: "Install"],
        "installingEllipsis": [.zh: "安装中…", .en: "Installing..."],
        "uninstallLanguageServer": [.zh: "卸载语言服务器", .en: "Uninstall Language Server"],
        "uninstallLanguageServerTitleFormat": [.zh: "卸载“%@”？", .en: "Uninstall \"%@\"?"],
        "uninstallLanguageServerMessage": [.zh: "只删除 YCode 原生数据目录中的服务器副本和安装记录，不修改系统工具。", .en: "Only the server copy and install record under YCode native data are removed. System tools are not modified."],
        "languageServiceFailed": [.zh: "语言服务操作失败", .en: "Language Service Operation Failed"],
        "installing": [.zh: "安装中", .en: "Installing"],
        "notInstalled": [.zh: "未安装", .en: "Not Installed"],
        "emptyProject": [.zh: "项目中没有文件", .en: "No Files in Project"],
        "confirmDelete": [.zh: "确认删除", .en: "Confirm Delete"],
        "deleteTitleFormat": [.zh: "删除“%@”？", .en: "Delete \"%@\"?"],
        "create": [.zh: "创建", .en: "Create"]
        ,
        "nothingNeedsAttention": [.zh: "目前无需处理", .en: "Nothing Needs Attention"],
        "attentionHint": [.zh: "Agent 完成或等待批准时会出现在这里。", .en: "Agent completion and approval requests appear here."],
        "attentionFooter": [.zh: "这里只负责定位；批准操作仍在 Agent 终端中完成。", .en: "This only navigates; approvals still happen in the agent terminal."],
        "needsHandling": [.zh: "需要处理", .en: "Needs Handling"],
        "turnComplete": [.zh: "已完成一轮", .en: "Turn Complete"],
        "justNow": [.zh: "刚刚", .en: "Just now"],
        "secondsAgoFormat": [.zh: "%d 秒前", .en: "%d seconds ago"],
        "minutesAgoFormat": [.zh: "%d 分钟前", .en: "%d minutes ago"],
        "hoursAgoFormat": [.zh: "%d 小时前", .en: "%d hours ago"],
        "noClaudeOrCodex": [.zh: "当前没有配置 Claude Code 或 Codex。", .en: "Claude Code or Codex is not configured."],
        "agentNotificationHooks": [.zh: "Agent 通知 hooks", .en: "Agent Notification Hooks"],
        "hookHelp": [.zh: "Codex 已有自定义 notify 时不会覆盖；可选择链式接入，卸载后会恢复原命令。", .en: "Existing custom Codex notify commands are not overwritten; chain mode can be selected and uninstall restores the original command."],
        "todoMCPPermission": [.zh: "允许 Agent 读取和修改当前项目待办", .en: "Allows the agent to read and modify current project todos"],
        "transport": [.zh: "传输", .en: "Transport"],
        "dataRouting": [.zh: "数据路由", .en: "Data Routing"],
        "terminalIDProjectDirectory": [.zh: "终端 ID / 项目目录", .en: "Terminal ID / project directory"],
        "todoMCPHelp": [.zh: "注册会立即修改对应 Agent 的用户配置，并只管理 ycode-todos 条目；卸载不会移除其他 MCP 服务。首次修改前会保留 .ycode.bak 备份。", .en: "Registration immediately changes the agent user config and only manages ycode-todos entries. Uninstall does not remove other MCP servers. A .ycode.bak backup is kept before the first change."],
        "ycodeCommand": [.zh: "ycode 命令", .en: "ycode Command"],
        "ycodeCommandHelp": [.zh: "在终端运行 ycode . 打开当前项目", .en: "Run ycode . in a terminal to open the current project"],
        "deepLink": [.zh: "ycode:// 深链", .en: "ycode:// Deep Link"],
        "deepLinkHelp": [.zh: "支持激活应用及 open?path=…", .en: "Supports app activation and open?path=..."],
        "systemIntegration": [.zh: "系统集成", .en: "System Integration"],
        "systemIntegrationHelp": [.zh: "命令安装到 /usr/local/bin/ycode。已有非 YCode 文件时不会覆盖；卸载也只移除 YCode 自己的符号链接。若系统还装有其他 YCode 版本，ycode:// 的默认处理器由 macOS 决定。", .en: "The command installs to /usr/local/bin/ycode. Existing non-YCode files are not overwritten; uninstall only removes YCode's own symlink. If another YCode version is installed, macOS decides the default ycode:// handler."],
        "integrationFailed": [.zh: "集成配置失败", .en: "Integration Configuration Failed"],
        "notDeclared": [.zh: "未声明", .en: "Not Declared"],
        "defaultHandler": [.zh: "默认处理器", .en: "Default Handler"],
        "declaredOtherDefault": [.zh: "已声明，其他版本为默认", .en: "Declared; another version is default"],
        "remove": [.zh: "移除", .en: "Remove"],
        "needsRepair": [.zh: "需要修复", .en: "Needs Repair"],
        "repair": [.zh: "修复", .en: "Repair"],
        "pathOccupied": [.zh: "路径已占用", .en: "Path Occupied"],
        "recheck": [.zh: "重新检查", .en: "Recheck"],
        "connected": [.zh: "已连接", .en: "Connected"],
        "notConnected": [.zh: "未连接", .en: "Not Connected"],
        "existingNotify": [.zh: "已有 notify", .en: "Existing notify"],
        "chainHook": [.zh: "链式接入", .en: "Chain Hook"],
        "registered": [.zh: "已注册", .en: "Registered"],
        "notRegistered": [.zh: "未注册", .en: "Not Registered"],
        "register": [.zh: "注册", .en: "Register"],
        "unregister": [.zh: "取消注册", .en: "Unregister"],
        "editAgent": [.zh: "编辑 Agent", .en: "Edit Agent"],
        "identifier": [.zh: "标识", .en: "Identifier"],
        "displayName": [.zh: "显示名称", .en: "Display Name"],
        "command": [.zh: "命令", .en: "Command"],
        "commandPrompt": [.zh: "gemini 或 /路径/命令", .en: "gemini or /path/to/command"],
        "argumentsOnePerLine": [.zh: "参数（每行一个）", .en: "Arguments (one per line)"],
        "environmentKeyValue": [.zh: "环境变量（每行 KEY=VALUE）", .en: "Environment variables (one KEY=VALUE per line)"],
        "doneButton": [.zh: "完成", .en: "Done"]
        ,
        "notificationPermissionDenied": [.zh: "系统通知权限未开启。", .en: "System notification permission is not enabled."],
        "notificationDeliveryNotObserved": [.zh: "macOS 通知中心没有确认收到测试通知。", .en: "macOS Notification Center did not confirm the test notification."],
        "testNotificationDelivered": [.zh: "测试通知已送达。", .en: "Test notification delivered."],
        "permissionAllowed": [.zh: "已允许", .en: "Allowed"],
        "permissionAllowedBannersOff": [.zh: "已允许（横幅关闭）", .en: "Allowed (banners off)"],
        "permissionProvisional": [.zh: "临时允许", .en: "Provisionally allowed"],
        "permissionEphemeral": [.zh: "本次允许", .en: "Allowed this time"],
        "permissionDenied": [.zh: "系统已关闭", .en: "Disabled in system settings"],
        "permissionNotDetermined": [.zh: "尚未请求", .en: "Not requested"],
        "cleanWorkspace": [.zh: "工作区干净", .en: "Workspace clean"],
        "changesCountFormat": [.zh: "%d 个变更", .en: "%d changes"],
        "historySessionCountFormat": [.zh: "%d 个历史会话", .en: "%d history sessions"],
        "noRecoverableAgentFormat": [.zh: "没有可恢复 %@ 历史的 Agent 配置", .en: "No agent profile can recover %@ history"],
        "restoredSessionTitleFormat": [.zh: "恢复的 %@ 会话", .en: "Restored %@ Session"],
        "finding": [.zh: "查找中…", .en: "Finding..."],
        "noTodos": [.zh: "没有待办", .en: "No Todos"],
        "unfinishedTodosFormat": [.zh: "%d 个未完成", .en: "%d unfinished"],
        "scanningHistory": [.zh: "正在扫描历史…", .en: "Scanning history..."],
        "historyEventsStatusFormat": [.zh: "%d 个会话 · 当前 %d 条事件", .en: "%d sessions · %d current events"],
        "fileOutsideProjectFormat": [.zh: "文件不在当前项目中：%@", .en: "File is outside the current project: %@"],
        "definitionNotFound": [.zh: "没有找到定义", .en: "Definition not found"],
        "previewTabHelpFormat": [.zh: "预览标签；双击固定\n%@", .en: "Preview tab; double-click to pin\n%@"],
        "dragShellWidth": [.zh: "拖动调整左右 Shell 宽度", .en: "Drag to resize shell columns"],
        "dragShellHeight": [.zh: "拖动调整上下 Shell 高度", .en: "Drag to resize shell rows"],
        "projectWindowTitleFormat": [.zh: "%@ — 项目窗口", .en: "%@ - Project Window"],
        "noProjectsShort": [.zh: "暂无项目", .en: "No Projects"]
        ,
        "nameRequired": [.zh: "名称不能为空", .en: "Name cannot be empty"],
        "invalidName": [.zh: "名称不能包含“/”，也不能是“.”或“..”", .en: "Name cannot contain \"/\" and cannot be \".\" or \"..\""],
        "dirtyPathError": [.zh: "该路径包含未保存的编辑，请先保存或关闭对应标签。", .en: "This path contains unsaved edits. Save or close the related tab first."],
        "openExternalFailedFormat": [.zh: "打开外部编辑器失败：%@", .en: "Failed to open external editor: %@"],
        "noExternalEditor": [.zh: "没有可用于打开此文件的应用", .en: "No application is available to open this file"]
    ]
}

private struct YCodeLocalizationKey: EnvironmentKey {
    static let defaultValue = YCodeLocalization.zh
}

extension EnvironmentValues {
    var ycodeL10n: YCodeLocalization {
        get { self[YCodeLocalizationKey.self] }
        set { self[YCodeLocalizationKey.self] = newValue }
    }
}

extension YCodeWorkspacePanel {
    func localizedTitle(_ l10n: YCodeLocalization) -> String {
        switch self {
        case .terminal: l10n.text("terminal")
        case .history: l10n.text("history")
        case .files: l10n.text("files")
        case .changes: l10n.text("changes")
        case .todos: l10n.text("todos")
        }
    }
}

extension YCodeThemeOption {
    var nsBackground: NSColor { NSColor(hex: background) ?? .windowBackgroundColor }
    var nsSurface: NSColor { NSColor(hex: surface) ?? .controlBackgroundColor }
    var nsPanel: NSColor { NSColor(hex: panel) ?? .controlBackgroundColor }
    var nsText: NSColor { NSColor(hex: text) ?? .textColor }
    var nsTextSoft: NSColor { NSColor(hex: textSoft) ?? .secondaryLabelColor }
    var nsAccent: NSColor { NSColor(hex: accent) ?? .controlAccentColor }
    var nsTerminalBackground: NSColor { NSColor(hex: terminal.background) ?? nsBackground }
    var nsTerminalForeground: NSColor { NSColor(hex: terminal.foreground) ?? nsText }
    var nsTerminalCursor: NSColor { NSColor(hex: terminal.cursor) ?? nsAccent }
}

extension NSColor {
    convenience init?(hex: String) {
        var raw = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if raw.hasPrefix("#") { raw.removeFirst() }
        guard raw.count == 6, let value = Int(raw, radix: 16) else { return nil }
        self.init(
            calibratedRed: CGFloat((value >> 16) & 0xff) / 255.0,
            green: CGFloat((value >> 8) & 0xff) / 255.0,
            blue: CGFloat(value & 0xff) / 255.0,
            alpha: 1
        )
    }
}

extension Color {
    init(themeHex hex: String) {
        self = Color(nsColor: NSColor(hex: hex) ?? .windowBackgroundColor)
    }
}
