// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable mirror of [`AgentLaunchProfile`]. Carries every field the user
 * can change in the Settings UI (`args` / `env` included, unlike the
 * runtime [`AgentProfileView`] which only exposes display data).
 */
export type AgentLaunchProfileView = { id: string, display_name: string | null, command: string, args: Array<string>, env: { [key in string]?: string }, icon: string | null, icon_variant: string | null, color: string | null, introspect: string | null, };
