// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frontend-facing view of a configured agent profile. The `command`/`args`/
 * `env` fields are intentionally NOT exposed — those are launch-time
 * concerns and exposing them via IPC would let the webview poke holes in
 * process semantics.
 */
export type AgentProfileView = { id: string, display_name: string, kind: string, };
