// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCommand } from "./AgentCommand";
import type { FileLoc } from "./FileLoc";
import type { PermissionOption } from "./PermissionOption";
import type { PlanItem } from "./PlanItem";
import type { SessionState } from "./SessionState";
import type { ToolStatus } from "./ToolStatus";

export type AgentEvent = { "kind": "StateChanged", state: SessionState, } | { "kind": "AssistantText", chunk_id: string, text: string, final_chunk: boolean, } | { "kind": "UserEcho", text: string, } | { "kind": "ToolCallStarted", id: string, name: string, args_preview: string, locations: Array<FileLoc>, } | { "kind": "ToolCallUpdated", id: string, status: ToolStatus, output_preview: string | null, } | { "kind": "Plan", items: Array<PlanItem>, } | { "kind": "AvailableCommands", commands: Array<AgentCommand>, } | { "kind": "ModeChanged", mode_id: string, } | { "kind": "RequestPermission", request_id: string, tool_name: string, summary: string, options: Array<PermissionOption>, } | { "kind": "RawOutput", bytes: Array<number>, } | { "kind": "HeuristicState", label: string, } | { "kind": "Error", message: string, fatal: boolean, };
