// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnswerPermissionRequest = { session_id: string, request_id: string, option_id: string, };
