// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-platform GitHub release asset names. `None` for a platform means we
 * can't auto-install there (the UI shows the card disabled).
 */
export type AssetPattern = { darwin_aarch64: string | null, darwin_x86_64: string | null, linux_x86_64: string | null, linux_aarch64: string | null, windows_x86_64: string | null, };
