// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable mirror of [`ycode_config::CheckpointSettings`]. `keep: null`
 * means "keep every checkpoint".
 */
export type CheckpointSettingsView = { enabled: boolean, keep: number | null, };
