// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandSpec = { 
/**
 * Binary path, may include `${SERVER_DIR}`.
 */
binary: string, args: Array<string>, };
