// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentLaunchProfileView } from "./AgentLaunchProfileView";

/**
 * Editable mirror of [`ycode_config::Config`].
 */
export type ConfigView = { agents: Array<AgentLaunchProfileView>, };
