// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentLaunchProfileView } from "./AgentLaunchProfileView";
import type { CheckpointSettingsView } from "./CheckpointSettingsView";
import type { FontSizesView } from "./FontSizesView";
import type { NotificationSettingsView } from "./NotificationSettingsView";
import type { SessionOpenModeView } from "./SessionOpenModeView";
import type { StartupModeView } from "./StartupModeView";
import type { WorktreeSettingsView } from "./WorktreeSettingsView";

/**
 * Editable mirror of [`ycode_config::Config`].
 */
export type ConfigView = { agents: Array<AgentLaunchProfileView>, font_sizes: FontSizesView, notifications: NotificationSettingsView, 
/**
 * Active theme id. Mirrors the string from disk verbatim — the frontend
 * looks it up in its theme registry and falls back to "foundry" when the
 * id is unknown (lets future themes round-trip safely through older app
 * versions).
 */
theme: string, 
/**
 * UI language choice: `"zh"` / `"en"` / `"system"`. Mirrors
 * [`ycode_config::Config::locale`] verbatim — `"system"` stays
 * `"system"` so the UI keeps following the OS.
 */
locale: string, 
/**
 * Collapse the top bar into a hover-reveal strip. Mirrors
 * [`ycode_config::Config::auto_hide_top_bar`].
 */
auto_hide_top_bar: boolean, 
/**
 * What the window opens on. Mirrors [`ycode_config::StartupMode`].
 */
startup: StartupModeView, worktree: WorktreeSettingsView, checkpoints: CheckpointSettingsView, session_open_mode: SessionOpenModeView, };
