// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSessionRequest = { agent_profile_id: string, project_id: string, title: string, 
/**
 * When set, the freshly-spawned CLI is launched with `--resume <id>`
 * (claude) / `resume <id>` (codex) so it loads the existing on-disk
 * session jsonl as context. Used when the user clicks a row in the
 * sidebar's "History" panel.
 */
resume: string | null, };
