// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCountsView } from "./TokenCountsView";

/**
 * Usage grouped by calendar day (UTC, `YYYY-MM-DD`).
 */
export type DailyUsageView = { date: string, tokens: TokenCountsView, cost_usd: number, };
