// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the "Sessions" sidebar — describes a session jsonl that the
 * introspect scanner found on disk. Per plan §9.1.
 */
export type DiscoveredSessionView = { 
/**
 * "claude" / "codex".
 */
agent: string, 
/**
 * Native session UUID. `None` when the file is malformed.
 */
session_id: string | null, 
/**
 * Absolute path to the jsonl file.
 */
jsonl_path: string, 
/**
 * Bytes — useful to flag huge sessions to the UI.
 */
size_bytes: bigint, 
/**
 * Unix milliseconds — file mtime, used to sort the sidebar.
 */
modified_at_ms: bigint, 
/**
 * Human-readable title derived from the session's first user message
 * (or claude `summary` event). `None` when the file is too new / has
 * no user message yet. The sidebar shows this when present, falling
 * back to a short session id.
 */
title: string | null, };
