// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contents of a single file as UTF-8. Binary files surface a `is_binary` flag
 * so the editor can refuse to open them instead of rendering garbage.
 */
export type FileContents = { path: string, contents: string, is_binary: boolean, };
