// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified-diff snapshot for a single file. `patch` is the raw `git diff`
 * output (or, for untracked files, a synthesized full-add diff). Empty
 * patch + `is_untracked = false` means the file is tracked and unchanged.
 */
export type FileDiff = { path: string, patch: string, is_untracked: boolean, };
