// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the project file tree. `path` is forward-slash, relative to
 * the project repo root. Directories also appear as their own entry so the
 * frontend can build an expandable tree.
 */
export type FileEntry = { path: string, is_dir: boolean, };
