// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable mirror of [`ycode_config::FontSizes`]. Mirrored 1:1 — we only
 * duplicate the type so the ts-rs binding lives next to the rest of the
 * view types and stays a pure data envelope.
 */
export type FontSizesView = { ui: number, editor: number, terminal: number, };
