// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HEAD context for the "Changes" panel header — the current branch (or a
 * short SHA when detached) plus how far ahead/behind its upstream it sits.
 */
export type GitBranchInfo = { 
/**
 * Branch name, or an abbreviated commit SHA when in detached-HEAD state.
 */
head: string, 
/**
 * True when HEAD points at a commit rather than a branch.
 */
detached: boolean, 
/**
 * Tracking branch (e.g. `origin/main`), if one is configured.
 */
upstream: string | null, 
/**
 * Commits on HEAD not yet on the upstream.
 */
ahead: number, 
/**
 * Commits on the upstream not yet on HEAD.
 */
behind: number, };
