// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local branches for the Changes-panel branch switcher, with the checked-out
 * one flagged. Remote-tracking branches are intentionally excluded — this
 * drives a "switch to a local branch" menu, not a full ref browser.
 */
export type GitBranchListView = { 
/**
 * The currently checked-out branch, or `None` when HEAD is detached.
 */
current: string | null, 
/**
 * Every local branch name, in `git for-each-ref` order (alphabetical).
 */
branches: Array<string>, };
