// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Git layer produced a file patch. The Changes panel uses this to
 * expose only the operations that are meaningful for the visible content:
 * unstaged hunks can be staged or discarded, staged hunks can be unstaged,
 * and both branch-review and checkpoint hunks are read-only (they describe
 * history that is already committed, not pending working-tree state).
 */
export type GitDiffSource = "unstaged" | "staged" | "branch" | "checkpoint";
