// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatus } from "./GitFileStatus";

/**
 * One row in the "Changes" panel. `additions`/`deletions` come from
 * `git diff --numstat` for tracked files; untracked files report `additions`
 * = line count and `deletions` = 0.
 */
export type GitFileChange = { 
/**
 * Repo-relative path, forward-slash separated.
 */
path: string, status: GitFileStatus, additions: number, deletions: number, };
