// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an uncommitted file (relative to HEAD). The Changes panel shows
 * both staged and unstaged files — the `GitFileChange.staged` flag records
 * which side an entry sits on so the panel can render a stage checkbox. The
 * glyph here reflects the kind of change (add/modify/delete), collapsing the
 * porcelain X/Y pair into a single classification.
 */
export type GitFileStatus = "modified" | "deleted" | "untracked" | "added" | "other";
