// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Working-tree status of a file relative to its index entry. We only surface
 * the unstaged side here — staged changes are deliberately ignored by the
 * "Changes" panel per product decision. `Renamed` only fires when the rename
 * happens in the working tree (rare; typical rename is index-side).
 */
export type GitFileStatus = "modified" | "deleted" | "untracked" | "other";
