// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single-hunk mutation requested from the Review surface.
 */
export type GitHunkAction = "stage" | "unstage" | "discard";
