// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallStage } from "./InstallStage";

export type InstallProgress = { server_id: string, stage: InstallStage, 
/**
 * 0–100. `None` means "indeterminate" (e.g. running `npm install`,
 * where we don't get byte-level progress).
 */
percent: number | null, 
/**
 * Short human-readable status, e.g. "Downloading rust-analyzer 2024-08-01".
 */
message: string, };
