// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse phase of an in-flight install, surfaced to the UI for progress.
 */
export type InstallStage = "resolving" | "downloading" | "extracting" | "running_npm" | "finalizing";
