// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspInstallationView = { version: string, binary_path: string, installed_at_ms: bigint, };
