// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspInstallationView } from "./LspInstallationView";
import type { ServerManifest } from "./ServerManifest";

/**
 * Frontend-facing snapshot of one language server: its built-in manifest
 * merged with the user's local install state. The Settings → Languages
 * page renders one card per entry.
 */
export type LspManifestView = { manifest: ServerManifest, 
/**
 * `None` until the user installs this server.
 */
installation: LspInstallationView | null, 
/**
 * False on platforms the manifest doesn't list an asset for. The UI
 * shows the card disabled with an "Unsupported on this platform" hint.
 */
platform_supported: boolean, 
/**
 * False when an external dependency is missing (e.g. `npm` not on
 * PATH for npm-based installers). The UI surfaces the message so the
 * user knows what to install first.
 */
requirement_message: string | null, };
