// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable mirror of [`ycode_config::NotificationSettings`].
 */
export type NotificationSettingsView = { enabled: boolean, only_when_unfocused: boolean, };
