// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for `fs_open_in_external_editor`. `editor` is optional;
 * when absent we fall back to `$VISUAL`, then `$EDITOR`, then a sensible
 * platform default. Per plan §8.15.
 */
export type OpenInExternalEditorRequest = { path: string, editor: string | null, };
