// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanStep = { text: string, 
/**
 * "done" | "in_progress" | "todo" — kept as a plain string so we can
 * surface anything the agent emits without churn-recompiling enums.
 */
state: string, };
