// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

export type PlanItem = { id: string, title: string, status: ToolStatus, 
/**
 * 0 = highest priority. Roughly maps to ACP plan priorities.
 */
priority: number, };
