// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCountsView } from "./TokenCountsView";

/**
 * Usage rolled up for one registered project. Only populated by the
 * cross-project view (`get_all_usage`); the single-project view returns an
 * empty `by_project`.
 */
export type ProjectUsageView = { project_id: string, name: string, tokens: TokenCountsView, cost_usd: number, session_count: number, };
