// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frontend-facing snapshot of a project plus the count of its live sessions.
 */
export type ProjectView = { id: string, name: string, repo_path: string, created_at_ms: bigint, session_count: bigint, };
