// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyModeView } from "./ProxyModeView";

/**
 * Editable mirror of [`ycode_config::ProxySettings`].
 */
export type ProxySettingsView = { mode: ProxyModeView, 
/**
 * Manual-mode address for both HTTP and HTTPS. A missing scheme is
 * filled in as `http://` on the Rust side, so the UI can accept the
 * bare `host:port` people copy out of their proxy app.
 */
url: string, 
/**
 * Manual-mode `NO_PROXY`, comma-separated.
 */
no_proxy: string, };
