// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplayRequest = { session_id: string, 
/**
 * Replay events with `seq >= from_seq`. 0 returns the full transcript.
 */
from_seq: bigint, };
