// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One durable snapshot in an agent session's review timeline. Sequence zero
 * is the pre-launch baseline; later entries are completed turns and compare
 * against the immediately preceding checkpoint.
 */
export type ReviewCheckpointView = { id: string, session_id: string, session_title: string, agent_profile: string, sequence: number, kind: string, source: string | null, event_kind: string | null, body_preview: string | null, created_at_ms: bigint, has_previous: boolean, };
