// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search hit returned from the cross-session query. Per plan §8.13.
 */
export type SearchHit = { agent: string, session_id: string, jsonl_path: string, seq: bigint, ts_ms: bigint, preview: string, };
