// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandSpec } from "./CommandSpec";
import type { InstallSpec } from "./InstallSpec";

/**
 * A language server we know how to install and (in PR2) talk to.
 *
 * The wire form is used both as the IPC list payload and as the data the
 * installer reads — keeping a single struct removes the need for a second
 * "config" type just to pass parameters between modules.
 */
export type ServerManifest = { 
/**
 * Stable id, also used as the on-disk install directory name.
 */
id: string, 
/**
 * Pretty name shown in the UI.
 */
display_name: string, 
/**
 * Free-form description for the Settings card subtitle.
 */
description: string, 
/**
 * `textDocument.languageId` values this server claims, e.g.
 * `["typescript", "typescriptreact", "javascript", "javascriptreact"]`.
 */
language_ids: Array<string>, 
/**
 * Lower-case extensions (including the leading dot) the editor should
 * route to this server. Used by PR2 to pick which server handles a file.
 */
file_extensions: Array<string>, 
/**
 * Optional homepage URL, surfaced as a "Learn more" link in the UI.
 */
homepage: string | null, install: InstallSpec, 
/**
 * How to launch the installed server once present on disk. Paths inside
 * `binary` and `args` may contain the literal token `${SERVER_DIR}`,
 * expanded to the per-server install directory at spawn time.
 */
command: CommandSpec, };
