// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

/**
 * Frontend-facing snapshot of one session row.
 */
export type SessionView = { id: string, title: string, agent_profile: string, project_id: string, 
/**
 * Runtime status. `Running` iff a live `TerminalSession` is currently
 * driving this id; otherwise `Exited { code: last_exit_code }`.
 */
status: SessionStatus, 
/**
 * Unix milliseconds.
 */
created_at_ms: bigint, 
/**
 * Unix milliseconds.
 */
updated_at_ms: bigint, archived_at_ms: bigint | null, };
