// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors [`ycode_config::SessionOpenMode`].
 */
export type SessionOpenModeView = "new_pane" | "replace_focused";
