// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopReason } from "./StopReason";

/**
 * Lifecycle state of a session. Adapters emit
 * [`StateChanged`](super::AgentEvent::StateChanged) to announce transitions;
 * the orchestrator validates that the transition is allowed before committing
 * it to the session row.
 *
 * See `ycode-core::session::Session::apply` for the transition matrix.
 */
export type SessionState = { "type": "Initializing" } | { "type": "Idle" } | { "type": "Running", turn_id: string, } | { "type": "AwaitingPermission", request_id: string, tool: string, summary: string, } | { "type": "Cancelling" } | { "type": "Done", stop_reason: StopReason, } | { "type": "Error", message: string, };
