// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format mirror of [`TerminalStatus`]. Kept here (rather than deriving
 * `TS` on the terminal crate's enum) so the terminal crate stays free of
 * frontend-binding concerns.
 */
export type SessionStatus = { "type": "Running" } | { "type": "Exited", code: number | null, } | { "type": "Error", message: string, };
