// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCountsView } from "./TokenCountsView";

/**
 * One session's usage row in the usage table.
 */
export type SessionUsageView = { agent: string, session_id: string | null, title: string | null, jsonl_path: string, 
/**
 * Dominant model (the one accounting for the most tokens).
 */
model: string | null, tokens: TokenCountsView, cost_usd: number, first_ts_ms: number, last_ts_ms: number, message_count: number, };
