// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionState } from "./SessionState";

/**
 * Frontend-facing snapshot of one session row, parsed and lightly enriched.
 * Mirrors `ycode_core::SessionRecord` but with `state` already deserialized
 * so the webview doesn't need to re-parse.
 */
export type SessionView = { id: string, title: string, agent_profile: string, repo_root: string, worktree_path: string, branch: string, base_ref: string, state: SessionState, 
/**
 * Unix milliseconds.
 */
created_at_ms: bigint, 
/**
 * Unix milliseconds.
 */
updated_at_ms: bigint, archived_at_ms: bigint | null, 
/**
 * True iff a live `SessionRunner` is currently driving this row.
 */
is_live: boolean, };
