// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

/**
 * Frontend-facing snapshot of one session row.
 */
export type SessionView = { id: string, title: string, agent_profile: string, 
/**
 * Agent-native conversation id when known or generated for resume.
 */
agent_session_id: string | null, 
/**
 * Agent-native title/thread label emitted by the CLI, when observed.
 */
agent_thread_name: string | null, project_id: string, 
/**
 * Runtime status. `Running` iff a live `TerminalSession` is currently
 * driving this id; otherwise `Exited { code: last_exit_code }`.
 */
status: SessionStatus, 
/**
 * Unix milliseconds.
 */
created_at_ms: bigint, 
/**
 * Unix milliseconds.
 */
updated_at_ms: bigint, archived_at_ms: bigint | null, 
/**
 * Path of the session's isolated git worktree, when it runs in one.
 * `None` for shared-mode sessions — the UI shows the Merge affordance
 * only when this is set.
 */
worktree_path: string | null, 
/**
 * The branch this session's worktree merges back into (label for the
 * Merge button).
 */
base_branch: string | null, };
