// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spawn a raw PTY not associated with any project session — used by the
 * second-terminal panel for ad-hoc shell commands. The returned id can be
 * used with `write_pty` / `resize_pty` / `kill_pty_raw`.
 */
export type SpawnPtyRequest = { cwd: string, command: string, args: Array<string>, cols?: number | null, rows?: number | null, };
