// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spawn a raw PTY not associated with any project session — used by the
 * second-terminal panel for ad-hoc shell commands. The returned id can be
 * used with `write_pty` / `resize_pty` / `kill_pty_raw`.
 *
 * `cols`/`rows` set the PTY's initial geometry. They're optional only for
 * backward compat; in practice every caller should pass real fitted values.
 * Opening the PTY at the wrong size and then sending `resize_pty` races
 * shell startup: the SIGWINCH from the resize can land before the shell
 * has installed its handler (default action: ignore), so the shell keeps
 * `COLUMNS` at the initial size and renders its first prompt at the wrong
 * width. VS Code / Hyper / Tabby all dodge this by passing dimensions at
 * spawn time; see hermes-hq/hermes-ide#113 for the canonical write-up.
 */
export type SpawnPtyRequest = { cwd: string, command: string, args: Array<string>, cols?: number, rows?: number, };
