// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors [`ycode_config::StartupMode`]. The serde rename keeps the JSON
 * tag identical on both sides so the config file and the IPC payload read
 * the same.
 */
export type StartupModeView = "resume" | "overview" | "blank";
