// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the OS proxy configuration currently says, for the Settings page to
 * show under "follow the system". Read-only — a snapshot, not a setting.
 */
export type SystemProxyView = { 
/**
 * Resolved env pairs, upper-case spellings only (the lower-case
 * duplicates ycode also injects would just be noise in the UI).
 */
vars: Array<[string, string]>, 
/**
 * Set when the system is on a PAC script, which cannot be expressed as
 * proxy env vars — the UI explains that instead of showing "none".
 */
pac_url: string | null, };
