// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frontend-facing snapshot of a single todo item.
 */
export type TodoView = { id: string, project_id: string, title: string, 
/**
 * One of `todo` / `doing` / `done`.
 */
status: string, sort_order: bigint, 
/**
 * When the todo most recently entered `doing` (unix ms), or `None`.
 */
started_at_ms: bigint | null, 
/**
 * When the todo most recently entered `done` (unix ms), or `None`.
 */
done_at_ms: bigint | null, created_at_ms: bigint, updated_at_ms: bigint, };
