// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token counters for a usage rollup. `reasoning` is a subset of `output`
 * (Codex reasoning tokens), kept for display only and excluded from `total`.
 */
export type TokenCountsView = { input: number, output: number, cache_creation: number, cache_read: number, reasoning: number, total: number, };
