// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolStatus = { "type": "Pending" } | { "type": "Running" } | { "type": "Completed" } | { "type": "Failed" } | { "type": "Cancelled" };
