// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallStage } from "./InstallStage";

export type UiEventKind = { "type": "SessionAppeared" } | { "type": "SessionTouched" } | { "type": "SessionRemoved" } | { "type": "ProjectAppeared" } | { "type": "ProjectRemoved" } | { "type": "PtyOutput", data: string, } | { "type": "PtyExit", code: number | null, } | { "type": "TitleChanged", title: string, } | { "type": "JsonlChanged", agent: string, jsonl_path: string, } | { "type": "AgentTurnComplete", 
/**
 * Identifier of the CLI that fired the event — "claude", "codex",
 * or "unknown" when the helper was invoked without a source arg.
 */
source: string, 
/**
 * Specific event sub-kind from the hook: "stop" / "notification" /
 * "turn_complete". Lets the UI distinguish "done" from "needs
 * permission" without inspecting `source`.
 */
event_kind: string, 
/**
 * Short snippet of the last assistant message extracted from the
 * hook payload (Codex notify JSON's `last-assistant-message` field,
 * Claude's transcript jsonl tail). Truncated to ~200 chars before
 * emission so the renderer can drop it straight into the toast.
 * `None` when extraction failed (file missing, unknown agent, etc.)
 * — the Tauri shell falls back to the generic "finished its turn"
 * body.
 */
body_preview: string | null, } | { "type": "LspInstallProgress", stage: InstallStage, percent: number | null, message: string, } | { "type": "LspInstallFinished", ok: boolean, version: string | null, error: string | null, } | { "type": "LspUninstalled" } | { "type": "LspDiagnostics", server_id: string, uri: string, params: unknown, };
