// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UiEventKind = { "type": "SessionAppeared" } | { "type": "SessionTouched" } | { "type": "SessionRemoved" } | { "type": "ProjectAppeared" } | { "type": "ProjectRemoved" } | { "type": "PtyOutput", data: string, } | { "type": "PtyExit", code: number | null, } | { "type": "TitleChanged", title: string, } | { "type": "JsonlChanged", agent: string, jsonl_path: string, };
