// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiEventKind } from "./UiEventKind";

export type UiEvent = { session_id: string, kind: UiEventKind, };
