// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEvent } from "./AgentEvent";

export type UiEventKind = { "type": "SessionAppeared" } | { "type": "SessionTouched" } | { "type": "SessionRemoved" } | { "type": "Agent", event: AgentEvent, };
