// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnifiedEventKind } from "./UnifiedEventKind";

/**
 * One normalised event from a session jsonl line. `seq` is the line number
 * (0-indexed); `ts_ms` is unix-millis (or 0 when the source line carries
 * no timestamp).
 */
export type UnifiedEvent = { seq: bigint, ts_ms: bigint, agent: string, session_id: string, kind: UnifiedEventKind, };
