// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSummary } from "./DiffSummary";
import type { PlanStep } from "./PlanStep";
import type { ToolStatus } from "./ToolStatus";
import type { UnifiedRole } from "./UnifiedRole";

export type UnifiedEventKind = { "kind": "message", role: UnifiedRole, text: string, } | { "kind": "thinking", text: string, } | { "kind": "tool_use", tool: string, input_json: string, status: ToolStatus, } | { "kind": "tool_result", tool: string, output_excerpt: string, status: ToolStatus, } | { "kind": "plan", steps: Array<PlanStep>, } | { "kind": "edits", files: Array<DiffSummary>, } | { "kind": "permission", tool: string, summary: string, decided: string | null, } | { "kind": "unknown", raw_type: string, };
