// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What closing a session's worktree would put at risk. Computed *after* the
 * agent's PTY is killed, so the numbers are final — the agent can no longer
 * write. The UI confirms before archiving when either field is set.
 */
export type WorktreeCloseState = { 
/**
 * Uncommitted or untracked changes in the worktree — lost when it's removed.
 */
uncommitted: boolean, 
/**
 * Commits on the session branch not yet in its base branch. The branch is
 * kept on close, but goes orphan (no worktree, not surfaced in the UI).
 */
unmerged_commits: number, };
