// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeCloseActionView } from "./WorktreeCloseActionView";

/**
 * Editable mirror of [`ycode_config::WorktreeSettings`].
 */
export type WorktreeSettingsView = { isolate_by_default: boolean, branch_prefix: string, close_action: WorktreeCloseActionView, };
