// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyUsageView } from "./DailyUsageView";
import type { ModelUsageView } from "./ModelUsageView";
import type { ProjectUsageView } from "./ProjectUsageView";
import type { SessionUsageView } from "./SessionUsageView";
import type { TokenCountsView } from "./TokenCountsView";

/**
 * Everything the Usage screen renders for one workspace. Costs are offline
 * estimates (known model families only); see `ycode_introspect::usage`.
 */
export type WorkspaceUsageView = { totals: TokenCountsView, total_cost_usd: number, sessions: Array<SessionUsageView>, by_model: Array<ModelUsageView>, by_day: Array<DailyUsageView>, 
/**
 * Per-project breakdown. Empty for the single-project view.
 */
by_project: Array<ProjectUsageView>, };
