// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WriteFileRequest = { project_id: string, file_path: string, contents: string, };
