// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WritePtyRequest = { session_id: string, 
/**
 * Base64-encoded bytes. The webview encodes typed input + key sequences
 * here so binary-safe transports work uniformly.
 */
data: string, };
