// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overwrite a project file with new UTF-8 contents. Path traversal escaping
 * the repo is rejected — same enforcement as `read_file`.
 */
export type WriteFileRequest = { project_id: string, file_path: string, contents: string, };
