-- Project containers: a project owns a repo path and groups sessions.
-- See conversation 2026-05-10 + project_ycode_overview memory.

CREATE TABLE projects (
    id            TEXT PRIMARY KEY,            -- ULID generated by the app
    name          TEXT NOT NULL,
    repo_path     TEXT NOT NULL,
    created_at    INTEGER NOT NULL             -- unix ms
);

CREATE INDEX idx_projects_created ON projects(created_at DESC);

-- ON DELETE SET NULL: deleting a project disconnects (but does not erase)
-- its archived sessions. Live sessions are blocked from deletion at the
-- application layer (see ProjectRepo::delete), so SET NULL only fires for
-- historical rows.
ALTER TABLE sessions ADD COLUMN project_id TEXT REFERENCES projects(id) ON DELETE SET NULL;

-- Backfill: one project per distinct repo_root in existing sessions.
-- The id uses a `legacy-` prefix + 16 random hex chars; collisions are
-- astronomically unlikely and these rows are one-shot. Future projects
-- get real ULIDs from the application layer.
INSERT INTO projects (id, name, repo_path, created_at)
SELECT
    'legacy-' || lower(hex(randomblob(8))),
    repo_root,
    repo_root,
    (strftime('%s', 'now') * 1000)
FROM (SELECT DISTINCT repo_root FROM sessions);

UPDATE sessions
SET project_id = (
    SELECT id FROM projects WHERE projects.repo_path = sessions.repo_root
)
WHERE project_id IS NULL;

CREATE INDEX idx_sessions_project ON sessions(project_id);
