// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adapters declare their capabilities at construction time. The orchestrator
 * and UI gate features on these flags rather than sniffing event variants.
 *
 * Concretely: a PTY adapter advertises `structured_permissions: false`, and
 * the UI then renders the permission modal in a "this is a heuristic match,
 * review the surrounding output" mode rather than the structured-tool form.
 */
export type Capabilities = { 
/**
 * Adapter emits [`AssistantText`](super::AgentEvent::AssistantText) chunks.
 */
streaming_text: boolean, 
/**
 * Adapter emits structured `ToolCallStarted`/`ToolCallUpdated` events.
 * PTY adapters must set this to `false`.
 */
structured_tool_calls: boolean, 
/**
 * Adapter intercepts tool calls *before* execution and emits a structured
 * `RequestPermission`. PTY adapters set this to `false`; they may still
 * emit `RequestPermission` from heuristic matches, but the UI labels it
 * as a best-effort interception.
 */
structured_permissions: boolean, 
/**
 * Adapter emits `Plan` updates.
 */
plans: boolean, 
/**
 * Adapter supports cooperative cancel.
 */
cancel: boolean, 
/**
 * Adapter supports `session/set_mode` (ACP modes feature).
 */
modes: boolean, };
