// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionKind } from "./PermissionKind";

export type PermissionOption = { option_id: string, name: string, kind: PermissionKind, };
