// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StopReason = { "type": "EndTurn" } | { "type": "MaxTokens" } | { "type": "Cancelled" } | { "type": "Refusal" } | { "type": "Other", detail: string, };
